/*
 * Copyright 2017-2026 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.cdk.impl;

import io.micronaut.cdk.Cloud;
import io.micronaut.cdk.action.DeleteComponentBuilderFactory;
import io.micronaut.cdk.action.ResourceSpecConverter;
import io.micronaut.cdk.action.Spec;
import io.micronaut.cdk.action.SpecReferenceProvider;
import io.micronaut.cdk.action.delete.DeleteSpec;
import io.micronaut.cdk.annotations.CloudSpecific;
import io.micronaut.cdk.annotations.ComponentService;
import io.micronaut.cdk.command.ActionService;
import io.micronaut.cdk.component.Component;
import io.micronaut.cdk.component.ComponentReference;
import io.micronaut.cdk.impl.processing.ResourceSpecProcessor;
import io.micronaut.cdk.util.Assert;
import io.micronaut.context.BeanContext;
import io.micronaut.context.Qualifier;
import io.micronaut.context.annotation.Value;
import io.micronaut.core.annotation.NonNull;
import io.micronaut.core.io.scan.ClassPathResourceLoader;
import io.micronaut.inject.qualifiers.Qualifiers;
import jakarta.annotation.PostConstruct;
import jakarta.inject.Inject;
import jakarta.inject.Singleton;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.ConcurrentHashMap;

import static io.micronaut.cdk.Cloud.ANY;

/**
 * Default implementation of {@link ResourceSpecConverter}. For {@link DeleteSpec} creation, it relies on {@link ResourceSpecProcessor}
 * that produces {@link DeleteComponentBuilderFactory} implementations , which are qualified by
 * <ul>
 *     <li>{@link CloudSpecific} with the relevant cloud constant as a value</li>
 *     <li>{@link ComponentService} with the Spec's FQN as the Named value.</li>
 * </ul>
 * The factories are generated {@link Singleton} in the application context. The factory is searched in the application context, there's no special registry for them.
 * <p>
 * The spec-to-component mapping is read from {@link #COMPONENT_MAP_RESOURCE META-INF/cdk/type2Component.properties} which is also produced by the annotation processor.
 * All classpath jars are searched for these resources.
 * <p>
 * The implementation assumes deployment to Cloud specified by "cdk.cloud" property, if the Component instance
 * does not provide the target cloud.
 */
@Singleton
public final class ResourceSpecConverterImpl implements ResourceSpecConverter {
    /**
     * These resources are generated by {@link ResourceSpecProcessor}. In the properties
     * file each key represents a type qualified name. The value is a FQN of a Component class associated to the type.
     *
     */
    public static final String COMPONENT_MAP_RESOURCE = "META-INF/cdk/type2Component.properties";

    /**
     * The resource is generated by {@link ResourceSpecProcessor}. The properties file contains
     */
    public static final String COMPONENT_SPEC_RESOURCE = "META-INF/cdk/%s.components.properties";

    private static final Logger LOG = LoggerFactory.getLogger(ResourceSpecConverterImpl.class);

    /**
     * Marker class info meaning there's no data. Also used as a default map entry with no types registered/present.
     */
    private static final ComponentClassInfo NONE_SPEC = new ComponentClassInfo(null, null, null);

    private final BeanContext beanContext;
    private final ClassPathResourceLoader resourceLoader;
    private final ClassLoader classLoader;

    // @GuardedBy(self)
    private final Map<String, Class<Component>> componentMap = new ConcurrentHashMap<>();

    /**
     * For each cloud, contains a Map of Component > ComponentClassInfo. Initialized from {@link #buildCloudComponentsMap()}
     */
    private final Map<Cloud, Map<Class<Component<?>>, ComponentClassInfo>> cloudComponentsMap = new HashMap<>();

    private Cloud defaultCloud;

    /**
     * Creates a resource converter implementation. Types are loaded from the application context's classloader.
     *
     * @param beanContext    the application context
     * @param resourceLoader resource loader that loads registration maps
     */
    public ResourceSpecConverterImpl(BeanContext beanContext, ClassPathResourceLoader resourceLoader) {
        this.beanContext = beanContext;
        this.resourceLoader = resourceLoader;
        this.classLoader = resourceLoader.getClassLoader();
    }

    /**
     * The default target cloud.
     *
     * @return default target cloud.
     */
    public Cloud getDefaultCloud() {
        return defaultCloud;
    }

    /**
     * Sets the default target cloud. This is injected from configuration property {@code cdk.cloud}
     *
     * @param defaultCloud the default target.
     */
    @Inject
    public void setDefaultCloud(@Value("${cdk.cloud:OCI}") Cloud defaultCloud) {
        this.defaultCloud = defaultCloud;
    }

    /**
     * Loads resources and creates type maps.
     */
    @SuppressWarnings({"unchecked", "rawtypes"})
    @PostConstruct
    public void buildComponentTypeMap() {
        resourceLoader.getResources(COMPONENT_MAP_RESOURCE).forEach((URL resource) -> {
            try (InputStream is = resource.openStream()) {
                Properties props = new Properties();
                props.load(is);

                for (String key : props.stringPropertyNames()) {
                    String className = props.getProperty(key, "").trim();
                    if (!className.isEmpty()) {
                        LOG.debug("Adding component {} for type {}", className, key);
                        try {
                            Class<?> clazz = Class.forName(className, true, classLoader);
                            if (!Component.class.isAssignableFrom(clazz)) {
                                LOG.warn("Component class {} registered for {} does not implement {}",
                                        clazz, key, Component.class.getName());
                                continue;
                            }
                            LOG.atDebug().log("Registering component {} for {}", className, key);
                            componentMap.merge(key, (Class<Component>) clazz, (c1, c2) -> Component.class);
                        } catch (ClassNotFoundException e) {
                            LOG.warn("Component class {} registered for {} could not be loaded: {}",
                                    className, key, e.getMessage(), e);
                        }
                    }
                }

            } catch (IOException ex) {
                LOG.error("Error loading resource with Component Map {}", resource, ex);
            }
        });
    }

    @PostConstruct
    @SuppressWarnings("unchecked")
    public void buildCloudComponentsMap() {
        for (Cloud c : Cloud.values()) {
            String rn = String.format(COMPONENT_SPEC_RESOURCE, c.name());
            Map<Class<Component<?>>, ComponentClassInfo> map = new HashMap<>();
            resourceLoader.getResources(rn).forEach((URL resource) -> {
                try (InputStream is = resource.openStream()) {
                    Properties props = new Properties();
                    props.load(is);

                    for (String key : props.stringPropertyNames()) {
                        Class<Component<?>> component;
                        Class<Spec<?>> spec;
                        Class<DeleteSpec<?>> deleteSpec;

                        try {
                            Class<?> clazz = Class.forName(key, false, classLoader);
                            if (!Component.class.isAssignableFrom(clazz)) {
                                LOG.warn("Component class {} does not implement {}",
                                        key, Component.class.getName());
                                continue;
                            }
                            component = (Class<Component<?>>) clazz;
                        } catch (ClassNotFoundException e) {
                            LOG.warn("Component class {} could not be loaded: {}",
                                    key, e.getMessage(), e);
                            continue;
                        }

                        String types = props.getProperty(key);
                        if ("*".equals(types)) {
                            map.put(component, NONE_SPEC);
                            continue;
                        }
                        String[] classNames = types.split(",");
                        if (classNames.length != 2) {
                            LOG.warn("Invalid type specification for component {}: {}",
                                    key, types);
                            continue;
                        }

                        try {
                            Class<?> clazz = Class.forName(classNames[0], false, classLoader);
                            if (!Spec.class.isAssignableFrom(clazz)) {
                                LOG.warn("Spec class {} registered for {} does not implement {}",
                                        clazz, key, Spec.class.getName());
                                continue;
                            }
                            spec = (Class<Spec<?>>) clazz;
                        } catch (ClassNotFoundException e) {
                            LOG.warn("Spec class {} registered for {} could not be loaded: {}",
                                    classNames[0], key, e.getMessage(), e);
                            continue;
                        }
                        try {
                            Class<?> clazz = Class.forName(classNames[1], false, classLoader);
                            if (!DeleteSpec.class.isAssignableFrom(clazz)) {
                                LOG.warn("DeleteSpec class {} registered for {} does not implement {}",
                                        clazz, key, DeleteSpec.class.getName());
                                continue;
                            }
                            deleteSpec = (Class<DeleteSpec<?>>) clazz;
                        } catch (ClassNotFoundException e) {
                            LOG.warn("DeleteSpec class {} registered for {} could not be loaded: {}",
                                    classNames[0], key, e.getMessage(), e);
                            continue;
                        }

                        map.merge(component, new ComponentClassInfo(component, spec, deleteSpec), (a, b) -> NONE_SPEC);
                    }
                } catch (IOException ex) {
                    LOG.error("Error loading resource with Component Map {}", resource, ex);
                }
            });
            cloudComponentsMap.put(c, map);
        }
    }

    @Override
    public Class<? extends Component<?>> findComponentClass(DeleteSpec<?> resourceSpec) {
        Assert.notNull(resourceSpec, "resourceSpec cannot be null");
        if (resourceSpec.getComponentClass() != null) {
            //noinspection unchecked
            return (Class<? extends Component<?>>) resourceSpec.getComponentClass();
        }
        return findAssociatedComponentClass(resourceSpec);
    }

    @Override
    public Class<? extends Component<?>> findComponentClass(Spec<?> resourceSpec) {
        Assert.notNull(resourceSpec, "resourceSpec cannot be null");
        return findAssociatedComponentClass(resourceSpec);
    }

    @SuppressWarnings("unchecked")
    Class<? extends Component<?>> findAssociatedComponentClass(Object data) {
        Class<?> clazz = data.getClass();
        String key = clazz.getName();
        Class<? extends Component> c = this.componentMap.get(key);
        if (c != null) {
            return c == Component.class ? null : (Class<? extends Component<?>>) c;
        }

        while (clazz != Object.class) {
            clazz = clazz.getSuperclass();
            String key2 = clazz.getName();
            c = this.componentMap.get(key2);
            if (c != null && c != Component.class) {
                LOG.debug("Found component {} for superclass {} of {}", c, key2, key);
                break;
            }
        }
        if (c == null) {
            c = Component.class;
        }
        c = this.componentMap.merge(key, (Class<Component>) c, (c1, c2) -> Component.class);
        if (c == Component.class) {
            throw new UnsupportedOperationException("Cannot find component for " + data);
        }
        return (Class<? extends Component<?>>) c;
    }

    @SuppressWarnings("unchecked")
    static <T, N, C extends Component<N>> Collection<T> findBeansOfType(BeanContext ctx, Class<T> clazz,
                                                                        Class<C> componentClazz, Cloud cloud) {
        Qualifier<T> componentQ = CdkQualifiers.acceptsType(ComponentService.class, componentClazz);
        Qualifier<T> qualifier;

        if (cloud != null && cloud != ANY) {
            qualifier = Qualifiers.byQualifiers(
                    CdkQualifiers.byAnnotationValue(CloudSpecific.class, cloud),
                    componentQ);
        } else {
            qualifier = Qualifiers.byQualifiers(
                    CdkQualifiers.reject(CloudSpecific.class),
                    componentQ);
        }

        return ctx.getBeansOfType(clazz, qualifier);
    }

    @SuppressWarnings("unchecked")
    @Override
    public <S extends Spec<S>, D extends DeleteSpec<D>, T extends DeleteSpec.Builder<D, T>, N, C extends Component<N>> T deleteComponent(C existingComponent, S spec) {
        Cloud cloud = existingComponent.getCloud() == null ? getDefaultCloud() : existingComponent.getCloud();

        Collection<DeleteComponentBuilderFactory<S, D, T, N, C>> col = findBeansOfType(beanContext, DeleteComponentBuilderFactory.class, existingComponent.getClass(), cloud);
        // add cloud-less providers, if any
        col.addAll(findBeansOfType(beanContext, DeleteComponentBuilderFactory.class, existingComponent.getClass(), ANY));
        for (DeleteComponentBuilderFactory<S, D, T, N, C> f : col) {
            LOG.debug("Delete spec builder for spec {}: {}", existingComponent.getClass(), f);
            T res = f.deleteBuilder(existingComponent, spec);
            if (res != null) {
                return res;
            }
        }
        return null;
    }

    @Override
    @NonNull
    public Class<? extends Spec<?>> findSpecClass(Class<? extends Component> component, Cloud targetCloud) {
        return getClassInfo(component, targetCloud).specClass;
    }

    private @NonNull ComponentClassInfo getClassInfo(Class<? extends Component> component, Cloud targetCloud) {
        if (Assert.notNull(targetCloud, "targetCloud cannot be null") == ANY) {
            throw new IllegalArgumentException("targetCloud cannot ANY");
        }
        Map<Class<Component<?>>, ComponentClassInfo> cloudMap = cloudComponentsMap.get(targetCloud);
        if (cloudMap == null) {
            return NONE_SPEC;
        }
        return cloudMap.getOrDefault(component, NONE_SPEC);
    }

    @Override
    @NonNull
    @SuppressWarnings({"rawtypes", "unchecked"})
    public <S extends Spec<S>> Collection<ComponentReference> findReferencedComponents(S spec, Cloud cloud) {
        // PENDING: the 'cloud' parameter is a little redundant, as we have Specs for each resource + cloud; but
        // similar to DeleteSpec that gets generalized, we should not rely on that probably.
        Qualifier<SpecReferenceProvider> qual;

        if (cloud == ANY) {
            qual = CdkQualifiers.acceptsType(ActionService.class, spec.getClass());
        } else {
            qual = Qualifiers.byQualifiers(
                    CdkQualifiers.optionally(
                            CloudSpecific.class,
                            CdkQualifiers.byAnnotationValue(CloudSpecific.class, cloud)
                    ),
                    CdkQualifiers.acceptsType(ActionService.class, spec.getClass())
            );
        }
        List<ComponentReference> refs = new ArrayList<>();
        Collection<? extends SpecReferenceProvider> providers = beanContext.getBeansOfType(SpecReferenceProvider.class, qual);
        if (providers.isEmpty()) {
            throw new UnsupportedOperationException("Cannot find spec reference provider for type " + spec.getClass());
        }
        for (SpecReferenceProvider<Spec<?>> refProvider : providers) {
            Collection<ComponentReference> links = refProvider.findReferences(spec);
            if (links != null) {
                refs.addAll(links);
            }
        }
        return refs;
    }

    @Override
    @NonNull
    public Class<? extends DeleteSpec<?>> findDeleteSpecClass(@NonNull Class<? extends Component> component, Cloud targetCloud) {
        return getClassInfo(component, targetCloud).deleteSpecClass;
    }

    record ComponentClassInfo(Class<Component<?>> component, Class<Spec<?>> specClass,
                              Class<DeleteSpec<?>> deleteSpecClass) {
    }

}
